name: Lint test python files

on: [push]

jobs:
  must-pass-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AlwinW/actions-lint-python@master
        with:
          root-dir-list: "__test__/pass"
          packages: black pycodestyle flake8 pylint isort mypy
          max-line-length: 88
      - uses: AlwinW/actions-lint-python@master
        with:
          root-dir-list: "__test__/fail/linelength111.py"
          packages: black pycodestyle flake8
          max-line-length: 120

  must-fail-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AlwinW/actions-lint-python@master
        with:
          root-dir-list: "__test__"
          packages: black pycodestyle flake8 pylint isort mypy
        continue-on-error: true
