name: Python lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AlwinW/actions-lint-python@master
        with:
          root-dir-list: |
            test1
            test2
          packages:
            black
