name: Lint test python files

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AlwinW/actions-lint-python@master
        with:
          root-dir-list: "."
          packages: black flake8
          max-line-length: 120
